"""empty message

Revision ID: 405b8652c4a2
Revises: 7f1c81240628
Create Date: 2020-04-11 12:09:05.810813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405b8652c4a2'
down_revision = '7f1c81240628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vegetables', sa.Column('unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vegetables', 'unit')
    # ### end Alembic commands ###
