"""empty message

Revision ID: 9391b3f29977
Revises: 405b8652c4a2
Create Date: 2020-04-11 21:59:25.345574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9391b3f29977'
down_revision = '405b8652c4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('apt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'apartment', ['apt_id'], ['id'])
    op.create_foreign_key(None, 'vegetables', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vegetables', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'apt_id')
    op.drop_table('apartment')
    # ### end Alembic commands ###
