"""empty message

Revision ID: 9e8281192362
Revises: 9f99dc7cabf6
Create Date: 2020-04-13 18:21:51.642189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8281192362'
down_revision = '9f99dc7cabf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_total', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_total')
    # ### end Alembic commands ###
